<template>
  <Loading>
    <div class="loadingio-spinner-ripple-lmh4mlln0v9"><div class="ldio-w9lf8z91sj">
    <div></div><div></div>
    </div></div>
  </Loading>
</template>

<script>
// Import component
import Loading from 'vue3-loading-overlay';
// Import stylesheet
import 'vue3-loading-overlay/dist/vue3-loading-overlay.css';

export default {
  components: {
    Loading,
  },
};
</script>

<style type="text/css">
  @keyframes ldio-w9lf8z91sj {
    0% {
      top: 96px;
      left: 96px;
      width: 0;
      height: 0;
      opacity: 1;
    }
    100% {
      top: 18px;
      left: 18px;
      width: 156px;
      height: 156px;
      opacity: 0;
    }
  }.ldio-w9lf8z91sj div {
    position: absolute;
    border-width: 4px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: ldio-w9lf8z91sj 1s cubic-bezier(0,0.2,0.8,1) infinite;
  }.ldio-w9lf8z91sj div:nth-child(1) {
    border-color: #e90c59;
    animation-delay: 0s;
  }
  .ldio-w9lf8z91sj div:nth-child(2) {
    border-color: #46dff0;
    animation-delay: -0.5s;
  }
  .loadingio-spinner-ripple-lmh4mlln0v9 {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: #ffffff33;
  }
  .ldio-w9lf8z91sj {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  .ldio-w9lf8z91sj div { box-sizing: content-box; }
  /* generated by https://loading.io/ */
</style>
