<template>
  <Loading>
    <div class="loading-spinner">
      <div class="loading-inner">
        <div></div>
        <div></div>
      </div>
    </div>
  </Loading>
</template>

<script>
import Loading from 'vue3-loading-overlay';
import 'vue3-loading-overlay/dist/vue3-loading-overlay.css';

export default {
  components: {
    Loading,
  },
};
</script>

<style type="text/css">
  @keyframes loading-inner {
    0% {
      top: 96px;
      left: 96px;
      width: 0;
      height: 0;
      opacity: 1;
    }
    100% {
      top: 18px;
      left: 18px;
      width: 156px;
      height: 156px;
      opacity: 0;
    }
  }
  .loading-inner div {
    position: absolute;
    border-width: 4px;
    border-style: solid;
    opacity: 1;
    border-radius: 50%;
    animation: loading-inner 1s cubic-bezier(0,0.2,0.8,1) infinite;
    box-sizing: content-box;
  }
  .loading-inner div:nth-child(1) {
    border-color: #E87131;
    animation-delay: 0s;
  }
  .loading-inner div:nth-child(2) {
    border-color: #8DD0E5;
    animation-delay: -0.5s;
  }
  .loading-spinner {
    width: 200px;
    height: 200px;
    display: inline-block;
    overflow: hidden;
    background: transparent;
  }
  .loading-inner {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(1);
    backface-visibility: hidden;
    transform-origin: 0 0; /* see note above */
  }
  /* generated by https://loading.io/ */
</style>
